apiVersion: v1
kind: Service
metadata:
  name: API-BACKEND-api-service
spec:
  type: NodePort
  selector:
    app: API-BACKEND-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007